//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public short BlockID { get; set; }
        public string BlockMarketName { get; set; }
        public string BlockParkName { get; set; }
        public string BlockHospitalName { get; set; }
        public string BlockMasjidName { get; set; }
        public string BlockSchoolName { get; set; }
    }
}
