//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashMode
    {
        public short CashID { get; set; }
        public long CashAdvance { get; set; }
        public long CashBalance { get; set; }
        public System.DateTime BalanceDueDate { get; set; }
        public short PaymentID { get; set; }
    }
}
