//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionAgent
    {
        public short AgentID { get; set; }
        public string AgentName { get; set; }
        public string AgentEmail { get; set; }
        public string AgentAddress { get; set; }
        public string AgentPhoneNoPrimary { get; set; }
        public string AgentPhoneNoSeondary { get; set; }
        public string AgentCNIC { get; set; }
        public int AgentCommission { get; set; }
        public Nullable<int> AgentComissionPaid { get; set; }
        public Nullable<int> AgentCommissionBalance { get; set; }
        public bool IsBalancePaid { get; set; }
        public System.DateTime BalancePaidDate { get; set; }
    }
}
