//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public short CustID { get; set; }
        public string FullName { get; set; }
        public string FatherName { get; set; }
        public string HusbandName { get; set; }
        public string CNIC { get; set; }
        public int Age { get; set; }
        public string Occupation { get; set; }
        public string PhoneResidence { get; set; }
        public string PhoneOffice { get; set; }
        public string Mobile { get; set; }
        public string EmailAddress { get; set; }
        public string MailAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string KinName { get; set; }
        public string KinCustomerRelation { get; set; }
        public string KinContactPrimary { get; set; }
        public string KinContactSecondary { get; set; }
        public int KinAge { get; set; }
        public string KinSonWifeDaughterOf { get; set; }
        public string KinAddress { get; set; }
        public int CustIDFKey { get; set; }
    }
}
