//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdealResidenciaEntities : DbContext
    {
        public IdealResidenciaEntities()
            : base("name=IdealResidenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<CashMode> CashModes { get; set; }
        public virtual DbSet<CommissionAgent> CommissionAgents { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InstallmentMode> InstallmentModes { get; set; }
        public virtual DbSet<Investor> Investors { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Plot> Plots { get; set; }
        public virtual DbSet<PlotBooking> PlotBookings { get; set; }
    }
}
