//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentMode
    {
        public short InstallmentID { get; set; }
        public long AdvancePaid { get; set; }
        public long InstallmentAmount { get; set; }
        public short TotalInstallments { get; set; }
        public System.DateTime InstallmentPaymentDate { get; set; }
        public short PaymentID { get; set; }
    }
}
