//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotBooking
    {
        public int BookingID { get; set; }
        public int CustID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> InvestorID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public System.DateTime Date { get; set; }
    }
}
