//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealResidencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot
    {
        public short PlotID { get; set; }
        public string PlotSizeMarla { get; set; }
        public string PlotSizeSquareInch { get; set; }
        public string PlotStatus { get; set; }
        public string PlotType { get; set; }
        public string PlotStreetNo1 { get; set; }
        public string PlotStreetNo2 { get; set; }
        public string PlotStreetNo3 { get; set; }
        public Nullable<short> BookingID { get; set; }
        public short BlocKID { get; set; }
    }
}
